### ISSUE TITLE
in meteor click number no response

### ISSUE THREAD

**Issue by wyysf** [Urigo/meteor-angular-utils-pagination#2]
if (paginationService.isAsyncMode(paginationId)) {
start = 0;
} else {
start = (paginationService.getCurrentPage(paginationId) - 1) * itemsPerPage;
}
"paginationService.isAsyncMode(paginationId)" always true，so start always equal 0

**Comment by Urigo** [comment]
@wyysf can you make a reproduction with the new version that I can test?

**Comment by Urigo** [comment]
@wyysf closing as I've created a new version and you haven't provided reproduction
